title: QTools
description: Small, focused docs for QTools Unity Asset Store tools.
theme: just-the-docs

url: https://elliot-padfield.github.io
baseurl: "/qtools.github.io"
include:
  - pages

permalink: pretty

aux_links:
  QTools on GitHub: https://github.com/Elliot-Padfield/qtools.github.io

footer_content: >
  Documentation built with <a href="https://just-the-docs.com/">Just the Docs</a>.

sass:
  sass_dir: _sass

just_the_docs:
  custom_css:
    - custom
